### ISSUE TITLE
Possiblity to reevaluate samples

### ISSUE THREAD

**Issue by LArnoldt** [ssciwr/sample_flow#81]
Since there is always the possibility that someone is ill/ a probe got missing etc. it would be great if old submitted samples could be reloaded to the current samples in the admin tab. Would this be possible?

**Comment by lkeegan** [comment]
This sounds a little tricky to do safely
- probably need to request a new primary key to ensure there is space in the current week for the reloaded sample
- there would then be a mismatch between the primary key as written on the test tube and the one in the samples table

Maybe one possibility:

- sample `22_46_C7` wasn't processed in week 46
- in week 47 admin clicks on a "redo" button next to this sample
- this requests a new sample `22_47_B2` with the same ref seq etc
  - the new sample would also contain the original primary key as written on the test tube

For this we would need to add a new field, e.g. `tube_primary_key` to the samples table with what is written on the test tube.
- for normal samples this would match the primary key
- for a reloaded sample this would be different from the primary key
- I guess this would rely on the person putting the test tubes in noticing they are from a previous week and then looking up the correct location from the samples table?

Or maybe I'm misunderstanding what you want?

**Comment by LArnoldt** [comment]
This is exactly what I meant!
