### ISSUE TITLE
Placeholder: upload file with multiple fastas

### ISSUE THREAD

**Issue by EdGreen21** [ssciwr/sample_flow#86]

**Comment by EdGreen21** [comment]
here is an example multifasta file (with .txt extension for git). This should be easy to parse, but how best to include in our pipeline? Could be a key part of making our sequencing pipeline compatible with our synthesis pipeline (where we would routinely be making 96 constructs at one) [Example_multifasta.fa.txt](https://github.com/ssciwr/circuit_seq/files/10280298/Example_multifasta.fa.txt)

**Comment by LArnoldt** [comment]
can be closed due to current developments
